### ISSUE TITLE
link-citations fails for those not in parentheses

### ISSUE THREAD

**Issue by tombeesley** [wjschne/apaquarto#64] opened 2024-05-10 12:28 UTC
I assume this is a template issue - apologies if not

![image](https://github.com/wjschne/apaquarto/assets/16871255/135c95b7-a7c0-487a-ac64-333d9a9c25f0)

**Comment by wjschne** [comment] 2024-05-11 22:01
I believe it is fixed in the most recent update. Let me know if the issue is resoved.

**Closed** 2024-05-13 20:35 UTC
